language: node_js
sudo: true
node_js:
- 8.11.1
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - github.com
  - gitlab.com
before_install:
- npm install -g npx
- npm install -g pm2
- npm install -g cpx
- bash ./.travis/scripts/init.sh
- bash ./.travis/scripts/clone.sh
script:
- npm install
- CI=false npm run build
- bash ./.travis/scripts/deploy.sh
branches:
  only:
  - master
  - dev
  - release
